name: Build and Push Docker Image to GitHub Container Registry

on:
  push:
    branches:
      - main 
    paths:
      - 'aws/Dockerfile' 
      - 'aws/inference.py'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }} 

      - name: Build Docker image
        run: |
          cd aws
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest .

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
